- project:
    name: ceph-volume-ansible-prs-lvm
    distro:
      - xenial
      - centos7
    objectstore:
      - bluestore
      - filestore
    scenario:
      - create
    subcommand:
      - lvm

    jobs:
      - 'ceph-volume-prs-{subcommand}-{distro}-{objectstore}-{scenario}'

- project:
    name: ceph-volume-ansible-prs-simple
    distro:
      - xenial
      - centos7
    objectstore:
      - bluestore
      - filestore
    scenario:
      - activate
    subcommand:
      - simple

    jobs:
      - 'ceph-volume-prs-{subcommand}-{distro}-{objectstore}-{scenario}'


- job-template:
    name: 'ceph-volume-prs-{subcommand}-{distro}-{objectstore}-{scenario}'
    display-name: 'ceph-volume {subcommand}: Pull Request [{distro}-{objectstore}-{scenario}]'
    node: vagrant&&libvirt
    concurrent: true
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
    discard-old-builds: true
    logrotate:
      daysToKeep: 30

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

      # this is injected by the ghprb plugin, and is fully optional but may help in manually triggering
      # a job that can end up updating a PR
      - string:
          name: ghprbSourceBranch
          description: "When manually triggered, and the remote PR isn't a branch in the ceph.git repo This can be specified to determine the actual branch."
      - string:
          name: GITHUB_SHA
          description: "The tip (last commit) in the PR, a sha1 like 7d787849556788961155534039886aedfcdb2a88 (if set, will report status to Github)"


    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          only-trigger-phrase: true
          trigger-phrase: '^jenkins test ceph-volume {subcommand} {distro}-{objectstore}-{scenario}|jenkins test ceph-volume all.*|jenkins test ceph-volume {subcommand} all.*'
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "ceph-volume {subcommand} testing {distro}-{objectstore}-{scenario}"
          started-status: "ceph-volume {subcommand} running {distro}-{objectstore}-{scenario}"
          success-status: "ceph-volume {subcommand} {distro}-{objectstore}-{scenario} OK"
          failure-status: "ceph-volume {subcommand} {distro}-{objectstore}-{scenario} failed"

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            DISTRO={distro}
            OBJECTSTORE={objectstore}
            SUBCOMMAND={subcommand}
            GITHUB_REPOSITORY="ceph/ceph"
            GITHUB_STATUS_CONTEXT="ceph-volume {subcommand} testing {distro}-{objectstore}-{scenario}"
            GITHUB_STATUS_STARTED="running"
            GITHUB_STATUS_SUCCESS="OK"
            GITHUB_STATUS_FAILURE="failed"
            GITHUB_STATUS_ERROR="completed with errors"
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true

    publishers:
      - postbuildscript:
          script-only-if-succeeded: False
          script-only-if-failed: True
          builders:
            - shell:
                !include-raw-escape:
                  - ../../../scripts/build_utils.sh
                  - ../../build/teardown
